blank_issues_enabled: false
contact_links:
  - name: 适配不支持的机型
    url: https://github.com/chase535/turbo-charge/issues/84#issuecomment-1591033332
    about: 适配需要文件，但问题就在这，我也不知道需要哪些文件，之前收集过很多不适配的手机的各种文件，但是发现并没有需要的文件，而且没有的很彻底，所以我也无从下手，无法进行适配。
