name: CMake

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.zip'
      - '**.json'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches:
      - 'main'

env:
  HOME: "${{ github.workspace }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh git make cmake
      - name: Clone aarch64-linux-musl-gcc
        run: git clone https://github.com/chase535/aarch64-linux-musl-gcc.git ${HOME}/aarch64-linux-musl-gcc -b main --depth=1
      - name: Set C and C++ compiler
        run: |
          echo "CC=${HOME}/aarch64-linux-musl-gcc/bin/aarch64-linux-musl-gcc" >> ${GITHUB_ENV}
          echo "CXX=${HOME}/aarch64-linux-musl-gcc/bin/aarch64-linux-musl-g++" >> ${GITHUB_ENV}
      - name: Clone and build mimalloc
        run: |
          git clone https://github.com/microsoft/mimalloc.git ${HOME}/mimalloc -b master --depth=1
          mkdir -p ${HOME}/mimalloc/out/release
          cd ${HOME}/mimalloc/out/release
          cmake ../..
          make
          sudo make install
      - name: Build module
        run: |
          cmake -B build
          make -C build -j$(nproc --all)
      - name: Copy files into module directory
        run: |
          cp -f ${HOME}/README.md ${HOME}/LICENSE ${HOME}/module
          cp -f ${HOME}/build/turbo-charge ${HOME}/module/common
      - name : Zip and upload module
        uses: actions/upload-artifact@v4
        with:
          name: turbo-charge
          path: ${{ github.workspace }}/module/*
