name: CMake

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.zip'
      - '**.json'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh git cmake
      - name: Clone aarch64-linux-musl-gcc
        run: git clone https://github.com/chase535/aarch64-linux-musl-gcc.git ${{github.workspace}}/aarch64-linux-musl-gcc -b main --depth=1
      - name: Create directory
        run: mkdir -vp ${{github.workspace}}/build
      - name: Configure CMake
        run: |
          export CC="${{github.workspace}}/aarch64-linux-musl-gcc/bin/aarch64-linux-musl-gcc"
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
      - name: Build module
        run: |
          export CC="${{github.workspace}}/aarch64-linux-musl-gcc/bin/aarch64-linux-musl-gcc"
          cmake --build ${{github.workspace}}/build --config Release
      - name: Copy ELF file into module directory
        run: cp -f ${{github.workspace}}/build/turbo-charge ${{github.workspace}}/module/common/turbo-charge
      - name : Zip and upload module
        uses: actions/upload-artifact@v3
        with:
          name: turbo-charge
          path: ${{github.workspace}}/module/*
