name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Clone aarch64-linux-gnu-with-musl
      run: git clone https://github.com/chase535/aarch64-linux-gnu-with-musl.git ${{github.workspace}}/aarch64-linux-gnu-with-musl -b main --depth=1
    - name: Create directory
      run: mkdir -vp ${{github.workspace}}/build
    - name: Configure CMake
      run: |
        export CC="${{github.workspace}}/aarch64-linux-gnu-with-musl/musl/bin/musl-gcc"
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build module
      run: |
        export CC="${{github.workspace}}/aarch64-linux-gnu-with-musl/musl/bin/musl-gcc"
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Copy ELF file into module directory
      run: cp -af ${{github.workspace}}/build/turbo-charge ${{github.workspace}}/module/common/turbo-charge;
    - name : Zip and upload module
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: turbo-charge
        path: ${{github.workspace}}/module
