name: Sync To Gitee

on: 
  push: 
    branches:
      - 'main'

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        run: |
          mkdir -p ~/.ssh
          rm -vf ~/.ssh/*
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          echo "PubkeyAcceptedKeyTypes +ssh-rsa" >> ~/.ssh/config
          sudo chmod -R 0600 ~/.ssh
          sudo ssh -vT git@github.com
          git clone --mirror "git@github.com:chase535/turbo-charge.git" ${{ github.workspace }}/turbo-charge && cd ${{ github.workspace }}/turbo-charge
          git remote set-url --push origin "git@gitee.com:chase535/turbo-charge"
          git fetch -p origin
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror
