name: Sync To Gitee

on: 
  push: 
    branches:
      - 'main'

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          sudo chmod 0600 ~/.ssh/id_rsa
          sudo chmod 0644 /etc/ssh/ssh_config
          sudo echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          git clone --mirror "git@github.com:chase535/turbo-charge.git" ${{ github.workspace }}/turbo-charge && cd ${{ github.workspace }}/turbo-charge
          git remote set-url --push origin "git@gitee.com:chase535/turbo-charge"
          git fetch -p origin
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror
