name: Sync To Gitee

on:
  push: 
    branches: [ main ]
  delete:
    branches: [ main ]
  create:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:chase535/turbo-charge.git"
          destination-repo: "git@gitee.com:chase535/turbo-charge"
