name: Sync To Gitee

on: 
  push: 
    branches:
      - 'main'

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod -R 0600 ~/.ssh
          git clone --mirror "https://github.com/chase535/turbo-charge.git" "" && cd "$SOURCE_DIR"
          git remote set-url --push origin "https://gitee.com/chase535/turbo-charge"
          git fetch -p origin
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror
